### ISSUE TITLE
[Doc] Add hello world example

### ISSUE THREAD

**Issue by codeleongy** [Jake-00/theWayToGo_note#1]
let me write a simple example for beginner

**Comment by Jake-00** [comment]
Hi @codeleongy , thanks, we already got issue. Are you insterested in adding it in Documentation?

**Comment by codeleongy** [comment]
thanks for reply this issue. I am insterested to adding it in Documentation

**Comment by Jake-00** [comment]
I assigned you. Look forward to your pr!
